### PR TITLE
Create anishaga.md

### PR DESCRIPTION
**Pull request by anishaga**

### CODE REVIEW

**Comment by kuraakhilesh8230** [comment]
congrats you have completed the milestone-1 successfully and you are good to go🎉

**Comment by kuraakhilesh8230** [comment]
too many commits correct it and you have till sunday time

**Comment by anishaga** [comment]
> too many commits correct it and you have till sunday time

Sorry to bother you but can you please help me with any article or something to squash these commits. I am having a hard time understanding this. I asked on the Discord channel but not getting any help there.

**Comment by kuraakhilesh8230** [comment]
> > too many commits correct it and you have till sunday time
> 
> Sorry to bother you but can you please help me with any article or something to squash these commits. I am having a hard time understanding this. I asked on the Discord channel but not getting any help there.

1.git rebase -i HEAD~n
n=number of commits

2.replace pick with squash and not replace 1st pick start from 2nd one

**Comment by kuraakhilesh8230** [comment]
Sry you are rejected from this open-source challenge as you failed to correct your errors after commenting also

**Comment by kuraakhilesh8230** [comment]
sry you are rejected from this open source challenge because your pr is closed

**Pull request closed without merging**
