### PR TITLE
Challenge 5-8,10,12,15,16,18

### PR DESCRIPTION
**Pull request by NazimFilzer**

### CODE REVIEW

**Comment by NazimFilzer** [comment]
Created The Pull Req Again Because Yesterdays pull req was from other branch.. The branch wasnt mentioned by sir

**Comment by kuraakhilesh8230** [comment]
congrats you have completed the milestone-1 successfully and you are good to go🎉

**Comment by NazimFilzer** [comment]
> congrats you have completed the milestone-1 successfully and you are good to go🎉
Thanks for the verification🙂

**Comment by NazimFilzer** [comment]
image
Challenege 22

**Comment by kuraakhilesh8230** [comment]
1.checks failed (dco and lint )
2.too many commits
complete this by sunday to avoid rejection

**Comment by kuraakhilesh8230** [comment]
Sry you are rejected in open-source challenge as you fail to correct your errors in given time

**Pull request closed without merging**
