### PR TITLE
Challenge 5, 6, 7, 8, 9 & 10: Akash#2989

### PR DESCRIPTION
**Pull request by iakashbarman**
Added my details into new folder (itstheakash) in the contributors folder.

### CODE REVIEW

**Comment by itstheakash** [comment]
> ### Challenge 8

The itstheakash-2.md file got accidentally deleted, so have recreated it again. 

Screenshot (117)

**Comment by itstheakash** [comment]
> ### Challenge 9

Unwanted commits removed.

Screenshot (116)

**Comment by itstheakash** [comment]
> ### Challenge 10

File updated.

Screenshot (124)

**Comment by kuraakhilesh8230** [comment]
1.All checks have failed and attached ss in pr which should be there in issues

**Comment by kuraakhilesh8230** [comment]
hey you have time until tomorrow to correct your mistakes pls do this in order to stay in this challenge
checks failed
too many commits

**Comment by kuraakhilesh8230** [comment]
sry you are rejected from this open source challenge as you haven't corrected your mistakes

**Pull request closed without merging**
