### PR TITLE
challenge 5, 6, 7, 8, 10, 12, 15, 18, 19 and 22 done

### PR DESCRIPTION
**Pull request by rahulsrivastava1**
Confusion created so that I deleted and again doing challenge 5

### CODE REVIEW

**Comment by kuraakhilesh8230** [comment]
congrats you have completed the milestone-1 successfully and you are good to go🎉

**Comment by rahulsrivastava1** [comment]
challenge 22 -> website hosted on GitHub
1Day22Git

**Review by Mrjoy832 — CHANGES_REQUESTED** [review]
image

Raghav will be at 3rd position as main branch

**Comment by rahulsrivastava1** [comment]
> image
> 
> Raghav will be at 3rd position as main branch

I have changed as you suggested...please check @Mrjoy832

**Comment by kuraakhilesh8230** [comment]
Congratulations you have successfully completed milestone 3 and good to go 🎊

**Pull request closed without merging**
