### PR TITLE
Challenge 5 to 8

### PR DESCRIPTION
**Pull request by Pratyaksha462**
Challenge-5

### CODE REVIEW

**Comment by Mrjoy832** [comment]
# Checks Failed , toooooooo...........many commits😶

**Comment by Pratyaksha462** [comment]
Solving ASAP

**Comment by Pratyaksha462** [comment]
I am sorry but due to some glitches this pull requests got closed .
I have opened another one

**Comment by Mrjoy832** [comment]
> I am sorry but due to some glitches this pull requests got closed . I have opened another one

You should mention the link ASAP , and DM me regarding this once so that I can identify

**Pull request closed without merging**
