### PR TITLE
day1-22

### PR DESCRIPTION
**Pull request by warriorwizard**

### CODE REVIEW

**Comment by TeralaShivaKumar** [comment]
hello [warriorwizard](https://github.com/warriorwizard)
squash the commits to eligible for rewards

**Comment by warriorwizard** [comment]
> hello [warriorwizard](https://github.com/warriorwizard) squash the commits to eligible for rewards

image

squashed !!!

**Comment by TeralaShivaKumar** [comment]
Congratulations warriorwizard on successfully completing scaler open source challenge's milestone 1 and being consistent.As promised you will receive your tokens soon.

**Comment by warriorwizard** [comment]
image

**Comment by kuraakhilesh8230** [comment]
sry you are rejected from this open source challenge : 
not done challenge-18 and 20

**Pull request closed without merging**
