### PR TITLE
Challenge19

### PR DESCRIPTION
**Pull request by shubhansu-kr**
Creating a new pr to complete challenge19

### CODE REVIEW

**Comment by kuraakhilesh8230** [comment]
1.too many commits 
2.dco checks failed
complete this by sunday

**Comment by shubhansu-kr** [comment]
> 1.too many commits 2.dco checks failed complete this by sunday

Actually i forgot to sign the merge, and now whenever i try to signoff the merge, the prev merge is just replicated and number of commints multiplies, 
I will try to fix this issue by tommorow.

**Comment by kuraakhilesh8230** [comment]
Sorry you are rejected from this open source challenge as your pr is closed

**Comment by shubhansu-kr** [comment]
> Sorry you are rejected from this open source challenge as your pr is closed

I was trying to solve conflicts and closed it somehow. 
I learned a lot from this challenge, thank you for hosting such programs.

**Pull request closed without merging**
