### PR TITLE
Day 1 - 30: Krishna Agarwal 

### PR DESCRIPTION
**Pull request by MrKrishnaAgarwal**
Day 5 Challenge

image

### CODE REVIEW

**Comment by MrKrishnaAgarwal** [comment]
Day 6 Challenge

image

**Comment by MrKrishnaAgarwal** [comment]
Day 7 Challenge

image

Successfully rebased, squashed and force pushed the changes into 1 single commit.

**Comment by MrKrishnaAgarwal** [comment]
Day 8 Challenge

image

**Comment by MrKrishnaAgarwal** [comment]
Day 10 Challenge

image

Created commit with signoff: _Signed-off-by: Krishna Agarwal <dmkrishna.agarwal@gmail.com_

**Comment by MrKrishnaAgarwal** [comment]
<h3> These commits are for fixing the DCO error </h3>

**They doesn't count towards the challenge.**

**Comment by DaltonDeven** [comment]
Too many commits, perform squash of all challenges

**Comment by MrKrishnaAgarwal** [comment]
Day 12 - Squashed from 19 to 5 commits

**Comment by kuraakhilesh8230** [comment]
congrats you have completed the milestone-1 successfully and you are good to go🎉

**Comment by MrKrishnaAgarwal** [comment]
> congrats you have completed the milestone-1 successfully and you are good to go🎉

**Thanks @kuraakhilesh8230 and @DaltonDeven for helping and guidance 😄**

**Comment by MrKrishnaAgarwal** [comment]
Day 15 - 
[Added my name in challengers-list.md](https://github.com/scaleracademy/scaler-september-open-source-challenge/pull/515/commits/2c81da167403f01dc03cc829dd8b4f1f29b51229)

image

**Comment by MrKrishnaAgarwal** [comment]
[Day 16: Fixed Merge Conflicts](https://github.com/scaleracademy/scaler-september-open-source-challenge/pull/515/commits/a0b2b422059e0df1e0cc65a8d8cb1b1be9b21a93)

image

image

**Comment by MrKrishnaAgarwal** [comment]
**Day 18 - Created 2 Gists and submitted them in markdown file:**

See them [here](https://gist.github.com/MrKrishnaAgarwal)


image

**Comment by MrKrishnaAgarwal** [comment]
<h3> Day 19 - Linter Check </h3> 

**Status: Passed ✔**

image

**Comment by MrKrishnaAgarwal** [comment]
<h3> Day 22 - GitHub Pages </h3>

image


image


image

**Comment by DaltonDeven** [comment]
Verified for milestone-3 congrats

**Comment by MrKrishnaAgarwal** [comment]
> ### Verified for milestone-3, congrats

**Thanks a lot 🎉**

**Pull request closed without merging**
