### PR TITLE
 Challenge (30/30) by - Sanyam Jain

### PR DESCRIPTION
**Pull request by Sanyam-2026**
image

### CODE REVIEW

**Comment by Sanyam-2026** [comment]
Added the Changes Required in Challenge 6 
image

**Comment by kuraakhilesh8230** [comment]
congrats you have completed the milestone-1 successfully and you are good to go🎉

**Comment by Sanyam-2026** [comment]
# Challenge 22 - Host a Website using Github pages - This is my project that I submitted for Microsoft future ready talent internship
image

image

**Review by Mrjoy832 — CHANGES_REQUESTED** [review]
## challengers-list.md wrongly edited

**Comment by Sanyam-2026** [comment]
> ## challengers-list.md wrongly edited

Fixed it

**Comment by Mrjoy832** [comment]
## Milestone-2 done ✅

**Comment by DaltonDeven** [comment]
All Set To Go Verified for Milestone-3 Congrats👍

**Pull request closed without merging**
