### PR TITLE
Challenge : 18

### PR DESCRIPTION
**Pull request by trishit78**
Creating a pull request to complete challenge 5

### CODE REVIEW

**Comment by kuraakhilesh8230** [comment]
congrats you have completed the milestone-1 successfully and you are good to go🎉

**Comment by trishit78** [comment]
### Challenge 18
**added 2 gist in the gist-solutions.md**

challenge 18

**Comment by DaltonDeven** [comment]
Verified for Milestone-2 congrats👍

**Comment by kuraakhilesh8230** [comment]
not attached screenshot of challenge-22 do attach it to verify it successfully

**Comment by DaltonDeven** [comment]
Verified for milestone-3 congrats

**Pull request closed without merging**
