### PR TITLE
challenge 7 - 10

### PR DESCRIPTION
**Pull request by nik132-eng**

### CODE REVIEW

**Comment by nik132-eng** [comment]
challange 9
image

image



__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by nik132-eng** [comment]
day 10 completed 
image


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by TeralaShivaKumar** [comment]
Hello [nik132-eng](https://github.com/nik132-eng)

**Comment by TeralaShivaKumar** [comment]
Hello [nik132-eng](https://github.com/nik132-eng)
please squash all the commits and pass all DCO checks to eligible for rewards

**Comment by TeralaShivaKumar** [comment]
Hello [nik132-eng](https://github.com/nik132-eng)
please squash all the commits and pass all DCO checks to eligible for rewards and this is last chance.

**Comment by nik132-eng** [comment]
I tried previously 3-4 time but whenever I do that steps mention in DCO file it make doc more complicated

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Pull request closed without merging**
