### PR TITLE
challenge-5

### PR DESCRIPTION
**Pull request by ShardulDS**
Challenge - 5

### CODE REVIEW

**Comment by kuraakhilesh8230** [comment]
too many commits pls check it and do that once again 
you have until tomorrow time

**Comment by ShardulDS** [comment]
> too many commits pls check it and do that once again 
> you have until tomorrow time

Should I just squash them all into one ?

**Comment by kuraakhilesh8230** [comment]
congrats you have completed the milestone-1 successfully and you are good to go🎉

**Comment by ShardulDS** [comment]
Signed-off-by: ShardulDS <ssajnekar@gmail.com>

**Pull request closed without merging**
