### PR TITLE
Challenge 5 - 15

### PR DESCRIPTION
**Pull request by kunalvvs**
---
name: Kunal
github_user_name: Ckoding
---

### CODE REVIEW

**Comment by Ckoding** [comment]
Screenshot (110)

**Comment by Ckoding** [comment]
Screenshot (111)

**Comment by TeralaShivaKumar** [comment]
Hello [Ckoding](https://github.com/Ckoding)

**Comment by TeralaShivaKumar** [comment]
Hello [Ckoding](https://github.com/Ckoding)
Squash commits and pass DCO checks to eligible for rewards

**Comment by Ckoding** [comment]
> Hello [Ckoding](https://github.com/Ckoding) Squash commits and pass DCO checks to eligible for rewards

**Comment by TeralaShivaKumar** [comment]
Hello Ckoding
Last chance to squash all the commits adnpass DCO checks to eligible for rewards

**Pull request closed without merging**
