### PR TITLE
Challenge-12/30

### PR DESCRIPTION
**Pull request by Sandhya312**
Successfully added ***Sandhya312/Sandhya312.md*** in the contributor folder.

image

### CODE REVIEW

**Comment by Sandhya312** [comment]
Challenge - 06 : 

image

**Comment by Sandhya312** [comment]
Challenge -07 :   

image

**Comment by kuraakhilesh8230** [comment]
signed commits format are done correctly above and below "---" this should be given
Screenshot (208)

it should be like this

---
name: your_name
github_user_name: YOUR-GITHUB-USERNAME
url_of_github_issue: Link_of_the_github_issue_created_in_first_challenge
your_favroite_programming_language: Add your favorite programming language here
---

please correct it and complete it asap

**Comment by Sandhya312** [comment]
> signed commits format are done correctly above and below "---" this should be given Screenshot (208)
> 
> it should be like this
> 
> ## name: your_name
> github_user_name: YOUR-GITHUB-USERNAME
> url_of_github_issue: Link_of_the_github_issue_created_in_first_challenge
> your_favroite_programming_language: Add your favorite programming language here
> please correct it and complete it asap


**Done**

image

**Comment by kuraakhilesh8230** [comment]
congrats you have completed the milestone-1 successfully and you are good to go🎉

**Comment by Sandhya312** [comment]
@kuraakhilesh8230  Hey I closed my PR by mistake. PLease help me to reopen PR.

**Pull request closed without merging**
