### PR TITLE
Challenge 5 ,6 ,7, 8,9,10,12 & 15

### PR DESCRIPTION
**Pull request by sreejasaha19**

### CODE REVIEW

**Comment by sreejasaha19** [comment]
Challenge 6:
scaler_img3

scaler_img4

**Comment by sreejasaha19** [comment]
Challenge 10:
scaler1

scaler1

**Comment by sreejasaha19** [comment]
Challenge 12:
scaler1

**Comment by kuraakhilesh8230** [comment]
congrats you have completed the milestone-1 successfully and you are good to go🎉

**Comment by sreejasaha19** [comment]
Challenge 15:
scaler5
scaler2
scaler4

**Comment by sreejasaha19** [comment]
Please reopen this pull request..

**Comment by sreejasaha19** [comment]
This PR got closed unfortunately that's why I have created this new PR. I hope you will understand. So I created a new pull request.
My new Pull Request Link: https://github.com/scaleracademy/scaler-september-open-source-challenge/pull/1110

**Pull request closed without merging**
