### PR TITLE
Challenge 11/30 - Ankush Mallick

### PR DESCRIPTION
**Pull request by ankushmallick1100**
<h3>Challenge 5: Create a folder ankushmallick1100 and under that folder create a markdown file ankushmallick1100.md</h3>

### CODE REVIEW

**Comment by ankushmallick1100** [comment]
Challenge 6: Add URL of my issue in ankushmallick1100.md markdown file.

**Comment by ankushmallick1100** [comment]
<h3>Challenge 7: Sqashed previous commits of Challenge 5 and Challenge 6.</h3>

**Comment by ankushmallick1100** [comment]
<h3>Challenge 8: Make an another markdown file ankushmallick1100-2.md and add some details to this file.</h3>

**Comment by ankushmallick1100** [comment]
<h3>Challenge 9: Delete ankushmallick1100-2.md(Challenge 8) by reset, r.evert and push to the Pull Request.<h3>

**Comment by ankushmallick1100** [comment]
<h3>Added a signed commit and added my favouritte programming language in ankushmallick1100.md markdown file.</h3>

**Comment by Mrjoy832** [comment]
## CLosed PR & issue🤨....Sorry but You are out from the challenge

**Pull request closed without merging**
