### PR TITLE
Scaler September Open Source Challenge- Day-15/ Day-30

### PR DESCRIPTION
**Pull request by gavelprashant99**

### CODE REVIEW

**Comment by gavelprashant99** [comment]
Merged All commit as Required in Challenge 7

**Comment by TeralaShivaKumar** [comment]
Hello Prashant Goyal
squash all commits and  pass all DCO checks

**Comment by TeralaShivaKumar** [comment]
Hello gavelprashant99
There are lot of commits please squash them and I am giving you rewards this time.

**Comment by gavelprashant99** [comment]
Ok sir


Thanks

**Comment by gavelprashant99** [comment]
How to reopen pull request

**Pull request closed without merging**
