### PR TITLE
Itsanjalichaudhary   details

### PR DESCRIPTION
**Pull request by itsanjalichaudhary**

### CODE REVIEW

**Comment by itsanjalichaudhary** [comment]
image

**Comment by itsanjalichaudhary** [comment]
image

**Comment by itsanjalichaudhary** [comment]
Screenshot (110)

**Comment by kuraakhilesh8230** [comment]
Too many commits , correct it and it should be less than 4 commits
asap do this

**Comment by kuraakhilesh8230** [comment]
hey you have time until tomorrow to correct your mistakes pls do this in order to stay in this challenge
too many commits

**Comment by itsanjalichaudhary** [comment]
image

**Comment by kuraakhilesh8230** [comment]
checks failed 
you have time until tomorrow to correct this

**Comment by kuraakhilesh8230** [comment]
you have until sunday to correct your mistakes or else you will be rejected from this open source challenge
checks failed

**Comment by itsanjalichaudhary** [comment]
image

**Comment by itsanjalichaudhary** [comment]
Github : itsanjalichaudhary

**Comment by itsanjalichaudhary** [comment]
can you  help me how do I slove this issue ?

**Comment by kuraakhilesh8230** [comment]
sry you are rejected from this open source challenge as you haven't corrected your mistakes

**Pull request closed without merging**
