### PR TITLE
Create TeralaShivaKumar.md

### PR DESCRIPTION
**Pull request by TeralaShivaKumar**

### CODE REVIEW

**Comment by TeralaShivaKumar** [comment]
challenge 10
Screenshot 2022-09-10 203945

**Comment by TeralaShivaKumar** [comment]
Challenge 15 Added my name to the challengers-list.md file
Screenshot 2022-09-16 010604
Screenshot 2022-09-16 010647

**Comment by TeralaShivaKumar** [comment]
ggggggggggggggggggggg

**Comment by TeralaShivaKumar** [comment]
**Challenge-22**
Screenshot 2022-09-23 015539

**Comment by kuraakhilesh8230** [comment]
do challenge-20 correctly because all the screen shots should be attached starting from todo to done and in atlast the screen shot should show done with tick marks for all the files

**Comment by DaltonDeven** [comment]
Verified for milestone-2 congrats

**Pull request closed without merging**
