### PR TITLE
shubhrai2811

### PR DESCRIPTION
**Pull request by shubhrai2811**
Day 5

### CODE REVIEW

**Comment by shubhrai2811** [comment]
Is my day 10 milestone cleared?

**Comment by kuraakhilesh8230** [comment]
hey you have time until tomorrow to correct your mistakes pls do this in order to stay in this challenge
all checks failed
too many commits

**Comment by shubhrai2811** [comment]
I wasn't able to do since day 11 because of my exams so i just want to know
that did i clear the day 10 milestone?

**Comment by kuraakhilesh8230** [comment]
you have until sunday to correct your mistakes or else you will be rejected from this open source challenge
checks failed
too many commits

**Comment by kuraakhilesh8230** [comment]
sry you are rejected from this open source challenge as you haven't corrected your mistakes

**Pull request closed without merging**
