### PR TITLE
Challenge 15 by dynamo12364#8025 (cy2000yadav)

### PR DESCRIPTION
**Pull request by cy2000yadav**
Updated cy2000yadav.md file

### CODE REVIEW

**Comment by kuraakhilesh8230** [comment]
1.all checks failed 
2.too many commits
correct it asap

**Comment by cy2000yadav** [comment]
> 1.all checks failed 2.too many commits correct it asap

Successfully done all DCO error is gone

**Comment by cy2000yadav** [comment]
Yes done successfully please recheck it and verify my status.

https://github.com/scaleracademy/scaler-september-open-source-challenge/pull/789

**Comment by kuraakhilesh8230** [comment]
sry you are rejected from this open source challenge as your pr closed

**Comment by cy2000yadav** [comment]
Hi , Yesterday it was all perfect and completed all the task successfully I
don't know what happened to the PR please I have done lots of hard work
till day 15 challenge please let me continue the challenge , I also sended
you the PR that time and you also checked it , it was perfect but you said
there are lots of commits in the PR, but don't know what happened after it
and PR got closed , if possible give me a way to tackle , its a lots of
investment of time in my challenge and ard work and lots of expectations
will vanish away. I will be grateful if you me a way and let me continue
for the challenge and alot rewards.

**Pull request closed without merging**
