### PR TITLE
 Challenge (15/30) by Subhash Jain

### PR DESCRIPTION
**Pull request by subhashjain010**
image

### CODE REVIEW

**Comment by subhashjain010** [comment]
Here is the Screenshot of my Updated Repo with Desired Changes - 
image

**Comment by subhashjain010** [comment]
Here is the Screenshot of New Created file - 

image

**Comment by subhashjain010** [comment]
Done Changes According to Challenge 9 - 
image

**Comment by kuraakhilesh8230** [comment]
> Done Changes According to Challenge 9 - image

delete this from here , it should be in issue and you have done that ,so remove this that's it

do this correctly by seeing guide 
Screenshot (201)

**Comment by subhashjain010** [comment]
> > Done Changes According to Challenge 9 - image
> 
> delete this from here , it should be in issue and you have done that ,so remove this that's it
> 
> do this correctly by seeing guide Screenshot (201)

done changes according you said

**Comment by subhashjain010** [comment]
> > Done Changes According to Challenge 9 - image
> 
> delete this from here , it should be in issue and you have done that ,so remove this that's it
> 
> do this correctly by seeing guide Screenshot (201)

Link of issue is - https://github.com/scaleracademy/scaler-september-open-source-challenge/issues/101

**Comment by kuraakhilesh8230** [comment]
hey you have time until tomorrow to correct your mistakes pls do this in order to stay in this challenge
dco checks failed
not done signed commits correctly which is challenge 10

**Comment by subhashjain010** [comment]
Please help

**Pull request closed without merging**
