### PR TITLE
Challenge 5 to 8 and 10

### PR DESCRIPTION
**Pull request by ag278**

### CODE REVIEW

**Comment by ag278** [comment]
Challenge 6 
Commit with a message of "Updated readme.md"

**Comment by ag278** [comment]
Challenge 7 completed

**Comment by ag278** [comment]
Challenge 8 completed

**Comment by ag278** [comment]
Challenge 10 completed

**Comment by ag278** [comment]
Challenge 11

**Comment by kuraakhilesh8230** [comment]
sry you are rejected from this open source challenge as your pr is closed

**Pull request closed without merging**
