### PR TITLE
Challenge 5: Added details in contributor folder

### PR DESCRIPTION
**Pull request by raibove**

### CODE REVIEW

**Comment by Mrjoy832** [comment]
DCO failed and Too many commits...perform sqaush

**Comment by kuraakhilesh8230** [comment]
all checks failed and too many commits correct it asap

**Comment by kuraakhilesh8230** [comment]
you have until sunday to correct your mistakes or else you will be rejected from this open source challenge
checks failed

**Comment by kuraakhilesh8230** [comment]
sry you are rejected from this open source challenge as you haven't corrected your mistakes

**Pull request closed without merging**
